<a href="https://colab.research.google.com/github/InsightofSPb/Introduction_to_ML_and_Advanced_ML/blob/main/Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.datasets import mnist
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
import pandas as pd

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape((X_train.shape[0], -1))
print(X_train.shape)

(60000, 784)


In [ ]:
pca = PCA(n_components=56, svd_solver='full')
pca.fit(X_train)
print(f'Доля объяснённой дисперсии = {sum(pca.explained_variance_ratio_)}')
print(f'Веса = {pca.singular_values_}')

Доля объяснённой дисперсии = 0.8423701180014487
Веса = [141291.00226882 120817.18859621 112650.9232813  105291.96728785
 100077.18497144  94183.59653123  82040.1120459   77021.85990481
  75376.92118237  69631.23338052  65869.14984994  64509.13672727
  59410.04495956  58998.19511577  56985.71130705  55231.63286157
  52198.76402532  51250.98798496  49419.42656348  48694.43400434
  46831.35272599  45506.89087967  44289.55261136  43326.24911537
  42628.89710531  41551.60556396  40884.34009496  40219.49683824
  39140.33829805  37698.05953452  36793.24874955  36514.15838842
  35208.23268526  34736.7098881   34242.84614725  33440.6771581
  32255.80068128  31678.98295252  31469.54935573  31168.63163094
  30652.22890721  30249.91893803  29340.84835833  28620.89683421
  28141.04938787  27777.92102306  27288.76245885  26893.25016452
  26448.48956348  25731.64254312  25617.1725649   25366.52910888
  24675.01277668  24380.30037642  24175.92478978  23629.67881431]


In [ ]:
X_pca = pca.transform(X_train)
X_train, X_test, Y_train, Y_test = train_test_split(X_pca, y_train, test_size=0.3, random_state=95)

clf1 = OneVsRestClassifier(RandomForestClassifier(criterion='gini',min_samples_leaf=10,max_depth=20,
                                                  n_estimators=10,random_state=95)).fit(X_train,Y_train)


In [ ]:
pred1 = clf1.predict(X_test)
cm1 = confusion_matrix(Y_test,pred1)
print(cm1)

[[1643    0    8    3    3    7   20    6    8    3]
 [   2 1989   13    6    3    7    5    7    6    4]
 [  11   12 1661   23   10    7   11   28   38    8]
 [   5    5   55 1600    4   59    4   13   33   18]
 [   8   11   16    0 1603    9   24    8   16   71]
 [  22    3   11   68   14 1409   26    4   29   14]
 [  25    1   11    2    4   28 1720    0   11    0]
 [   9   19   22    7   35    7    1 1794   12   49]
 [  21   11   23   60   10   59    9    7 1480   25]
 [  14   12   10   26   73   11    3   34   14 1627]]


In [ ]:
clf2 = OneVsRestClassifier(LogisticRegression(solver='lbfgs', random_state=95)).fit(X_train,Y_train)

In [ ]:
pred2 = clf2.predict(X_test)
cm2 = confusion_matrix(Y_test,pred2)
print(cm2)

[[1651    0    4    6    3   13    8    3   11    2]
 [   1 1984   10    5    2   12    3    3   18    4]
 [   9   24 1579   32   30   14   33   33   44   11]
 [   9   11   57 1574    1   68    6   15   34   21]
 [   3    8   16    1 1615    2   18   11   21   71]
 [  30   10   28   77   34 1303   32    8   57   21]
 [  11    6   11    1    9   31 1715    6   12    0]
 [   7   10   36    7   29    6    0 1799    8   53]
 [  18   44   36   47   12   72   12    9 1418   37]
 [  18   15   14   24   87   25    0   58   17 1566]]


In [ ]:
clf3 = OneVsRestClassifier(DecisionTreeClassifier(criterion='gini',min_samples_leaf=10,
                                                  max_depth=20,random_state=95)).fit(X_train,Y_train)

In [ ]:
pred3 = clf3.predict(X_test)
cm3 = confusion_matrix(Y_test,pred3)
print(cm3)

[[1542    2   34   23    7   35   19    4   17   18]
 [   0 1960   30    4    5   13    6    6   10    8]
 [  27   13 1507   39   24   45   30   36   63   25]
 [  12    4   85 1460   13   85   14   27   73   23]
 [  18   14   41   10 1436   42   37   26   30  112]
 [  26   14   74   71   29 1221   31    9   90   35]
 [  31    6   37   20    8   52 1604   10   27    7]
 [   9   13   47   10   27   15    4 1725   31   74]
 [  20   17   99   85   17   72   10   22 1318   45]
 [  19   12   40   17  144   53    5   64   46 1424]]


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving pred_for_task.csv to pred_for_task.csv


In [ ]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded['pred_for_task.csv']), index_col='FileName')
print(df2.head())

          Label  f0  f1  f2  f3  f4  f5  f6  f7  f8  ...  f774  f775  f776  \
FileName                                             ...                     
file1         7   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file2         2   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file3         1   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file4         0   0   0   0   0   0   0   0   0   0  ...     0     0     0   
file5         4   0   0   0   0   0   0   0   0   0  ...     0     0     0   

          f777  f778  f779  f780  f781  f782  f783  
FileName                                            
file1        0     0     0     0     0     0     0  
file2        0     0     0     0     0     0     0  
file3        0     0     0     0     0     0     0  
file4        0     0     0     0     0     0     0  
file5        0     0     0     0     0     0     0  

[5 rows x 785 columns]


In [ ]:
df2ans = df2.loc[:,'Label'].values
df2tr = df2.drop(['Label'],axis=1).values


In [ ]:
trans =  pca.transform(df2tr)
print(trans)
f3 = trans[2, :].reshape(1, -1)
f1 = trans[0, :].reshape(1, -1)
f23 = trans[22, :].reshape(1, -1)
P1 = max(max(clf1.predict_proba(f3)))
P2 = max(max(clf2.predict_proba(f1)))
P3 = max(max(clf3.predict_proba(f23)))
print(f'Вероятность отнесения файла 3 к назначенному классу = {round(P1,3)}')
print(f'Вероятность отнесения файла 1 к назначенному классу = {round(P2,3)}')
print(f'Вероятность отнесения файла 23 к назначенному классу = {round(P3,3)}')


[[-332.27116927  747.7987162   -42.84481899 ...  -99.62568422
  -107.02936738    2.0453765 ]
 [  20.69696209 -955.58458273 -152.71551708 ... -128.24555526
    50.14902696  102.75736684]
 [-946.02686793 -430.84318261   66.17633643 ...   -4.05070048
    48.19941355  -61.12838724]
 ...
 [ 224.98822327  881.03842296 -180.92093117 ... -111.3587582
     3.52949783  120.65467586]
 [1128.03797971 -354.99535818 -183.85326766 ... -144.86439037
    99.92631283  -16.28537096]
 [-765.24057399 -154.13449942 -107.92304472 ... -100.21796955
    16.17037171 -131.68621811]]
Вероятность отнесения файла 3 к назначенному классу = 0.998
Вероятность отнесения файла 1 к назначенному классу = 0.915
Вероятность отнесения файла 23 к назначенному классу = 0.989
